#!/bin/sh

# the user has to be inside of the "video" group to not need sudo!

DMENU="dmenu -l 5 -p"

levels="0
5
20
60
99"

step=$(($(cat /sys/class/backlight/intel_backlight/max_brightness) / 100))
current=$(($(cat /sys/class/backlight/intel_backlight/brightness) / $step))

case "$1" in
    "-i") 
        if [ "$current" -eq "1" ]; then
            value=5
        else
            if [ "$(($current + 5))" -gt "100" ]; then
                value=100
            else
                value=$(($current + 5))
            fi
        fi
        ;;
    "-d")
        if [ "$current" -eq "1" ]; then
            value=0
        else
            if [ "$(($current - 5))" -lt "1" ]; then
                value=1
            else
                value=$(($current - 5))
            fi
        fi
        ;;
    "-s")
        value=$2
        ;;
    *)
        value=$(echo "$levels" | $DMENU " $current ")
        ;;
esac

if [ -n "$value" ]; then
    if [ "$value" -le "100" ]; then
        echo $(($value * $step)) > /sys/class/backlight/intel_backlight/brightness
    fi
    notify-send -a "brightness control" -t 1250 "set brightness to $value"
fi
