#!/bin/sh

DMENU="dmenu -l 10 -i"
SetBG="feh --bg-fill"
SetGif="$HOME/.config/jalupa_config/dmenuscripts/background/loadGif.sh"
BGFOLDER=$HOME/.config/jalupa_config/dmenuscripts/background

list="random
default
black
select picture
select gif
"

rmOld()
{
    to_kill=$(ps axo pid,args | grep 'loadGif.sh' | awk -e '{print $1}' | head -n 1)
    kill $to_kill
}

useGif ()
{
    selGif=$(find $BGFOLDER/ -name *.gif | $DMENU)
    if [ -n "$selGif" ]; then
        speed="0.$(echo " " | $DMENU -p "speed:")"
        if [ -n "$speed" ]; then
            rmOld
            $SetGif $speed $selGif
        fi
    fi
}

choice=$(echo "$list" | $DMENU)

case "${choice}" in
    "random")
        $SetBG --randomize $HOME/Pictures/Backgrounds
        ;;
    "default")
        rmOld
        $SetBG $HOME/Pictures/Backgrounds/currentBackground.jpg
        ;;
    "black")
        rmOld
        $SetBG $BGFOLDER/black.jpg
        ;;
    "select picture")
        BGjpg=$(find $HOME/Pictures/Backgrounds -name *.jpg)
        BGpng=$(find $HOME/Pictures/Backgrounds -name *.png)
        newBG=$(echo "$BGjpg\n$BGpng" | $DMENU)
        if [ -n "$newBG" ]; then
            rmOld
            $SetBG "$newBG" &
        fi
        ;;
    "select gif")
        useGif
        ;;
esac
