#!/bin/sh

DMENU="dmenu -l 7 -i"

fixes="keyboard
audio
screen
multi monitor
bluetooth
mousepad
touch"

toFix=$(echo -e "$fixes" | $DMENU)

case "$toFix" in
    "keyboard")

        setxkbmap eu
        setxkbmap -option caps:escape_shifted_capslock
        ;;
    "audio")
        pkill pulseaudio
        /bin/sh -c "pulseaudio --daemonize"
        ;;
    "screen")
        pkill picom
        picom --experimental-backends &
        ;;
    "multi monitor")
        xrandr --auto
        sleep 3
        setxkbmap -option caps:escape_shifted_capslock
        setxkbmap -layout "eu"        
        xrandr --auto --output DP-2-1 --right-of eDP-1
        sleep 1
        feh --bg-fill $HOME/Pictures/Backgrounds/currentBackground.jpg
        ;;
    "bluetooth")
        mpris-proxy & #allow bluetooth media control keys
        /bin/sh -c "pulseaudio --daemonize"
        ;;
    "mousepad")
        if [ "$(echo -e "activate\ndeactivate" | $DMENU)" = "activate" ]; then xinput enable 12; else xinput disable 12; fi
        ;;
    "touch")
        if [ "$(echo -e "activate\ndeactivate" | $DMENU)" = "activate" ]
        then 
            xinput enable "Wacom HID 523A Finger" && xinput map-to-output "Wacom HID 523A Finger" eDP-1
            xinput enable "Wacom HID 523A Pen" && xinput map-to-output "Wacom HID 523A Pen" eDP-1
            xinput enable "Wacom HID 523A Pen Pen (0xb350e15d)" && xinput map-to-output "Wacom HID 523A Pen Pen (0xb350e15d)" eDP-1
            xinput enable "Wacom HID 523A Pen Eraser (0xb350e15d)" && xinput map-to-output "Wacom HID 523A Pen Eraser (0xb350e15d)" eDP-1
        else 
            xinput disable "Wacom HID 523A Finger"
            xinput disable "Wacom HID 523A Pen"
            xinput disable "Wacom HID 523A Pen Pen (0xb350e15d)"
            xinput disable "Wacom HID 523A Pen Eraser (0xb350e15d)"
        fi
        ;;
    *)
        ;;
esac

