#!/bin/sh

DMENU="dmenu -l 7 -i"

fixes="keyboard
audio
screen
monitor
bluetooth
mousepad
touch
vpn"

toFix=$(echo "$fixes" | $DMENU)

case "$toFix" in
    "keyboard")
        setxkbmap -option caps:escape_shifted_capslock
        setxkbmap -layout "us,de" -variant "basic,nodeadkeys" -option grp:ctrls_toggle
        ;;
    "audio")
        pkill pulseaudio
        /bin/sh -c "pulseaudio --daemonize"
        ;;
    "screen")
        pkill picom
        picom --experimental-backends &
        ;;
    "monitor")
        xrandr --output DP-0 --mode 2560x1440 --rate 239.96 --left-of HDMI-0
        ;;
    "bluetooth")
        mpris-proxy & #allow bluetooth media control keys
        /bin/sh -c "pulseaudio --daemonize"
        ;;
    "mousepad")
        if [ "$(echo "activate\ndeactivate" | $DMENU)" = "activate" ]; then xinput enable 12; else xinput disable 12; fi
        ;;
    "touch")
        if [ "$(echo "activate\ndeactivate" | $DMENU)" = "activate" ]; then xinput enable 10 && xinput map-to-output 10 eDP-1; else xinput disable 10; fi
        ;;
    "vpn")
        nmcli con down pvpn-ipv6leak-protection
        ;;
    *)
        ;;
esac

