#!/bin/sh

DMENU="dmenu -l 10 -i"
processes=$(ps axo user,pid,args | sed -n -e "s/$USER\s*//p")

choice=$(echo "$processes" | $DMENU)

if [ -n "$choice" ]; then
    kill -9 $(echo "$choice" | awk -e '{print $1}')
fi
