#!/bin/bash

DMENU="dmenu -l 12 -i"

MUSICFOLDER=$HOME/Music
PLAYER="mpv --no-video"
PLAYERTOKILL="mpv"

play ()
{
    pkill $PLAYERTOKILL
    $PLAYER "$1"
}

musicFromLink ()
{
    link=$(echo "stop
50s
60s
80s
90s
jazz
jazz 2
jazz funk
funk
reggae
soul
southern soul
R&B
afrobeat
exotica vintage
rock
DEF CON
kpop
anime" | $DMENU)

if [ -n "$link" ]; then

    case $link in
        "stop")
            pkill $PLAYERTOKILL
            ;;
        "50s")
            play https://zeno.fm/radio/50s-rewind
            ;;
        "60s")
            play https://zeno.fm/radio/60s-rewind
            ;;
        "80s")
            play https://zeno.fm/radio/80s-rewind
            ;;
        "90s")
            play https://zeno.fm/radio/90s-rock
            ;;
        "jazz")
            play https://zeno.fm/radio/gaslight-sqare-jazz
            ;;
        "jazz 2")
            play https://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3
            ;;
        "jazz funk")
            play https://zeno.fm/radio/kjgr-jazz-grooves
            ;;
        "funk")
            play https://zeno.fm/radio/oldschool-radio
            ;;
        "reggae")
            play https://somafm.com/reggae.pls
            ;;
        "soul")
            play https://somafm.com/7soul.pls
            ;;
        "southern soul")
            play https://zeno.fm/radio/kssr-southern-soul-radio
            ;;
        "afrobeat")
            play https://zeno.fm/radio/roots-n-rhythm-radio
            ;;
        "R&B")
            play https://zeno.fm/radio/classic-sounds-radio
            ;;
        "exotica vintage")
            play https://somafm.com/illstreet.pls
            ;;
        "rock")
            play https://zeno.fm/radio/electric-circus-radio
            ;;
        "DEF CON")
            play https://somafm.com/defcon.pls
            ;;
        "kpop")
            play https://zeno.fm/radio/kpopfmbuyd6kezuk8uv
            ;;
        "anime")
            play https://zeno.fm/radio/radio-gambaru
            ;;
        *)
            ;;
    esac
else
    main
fi
}

background ()
{
    link=$(echo "stop
fluid
hip hop lofi
japanese
japanese lofi
deep space
ambient" | $DMENU)

if [ -n "$link" ]; then
    case $link in
        "stop")
            pkill $PLAYERTOKILL
            ;;
        "fluid")
            play https://somafm.com/fluid.pls
            ;;
        "hip hop lofi")
            play https://zeno.fm/radio/lofi-hip-hop-radio
            ;;
        "japanese")
            play https://zeno.fm/radio/japanese-styles
            ;;
        "japanese lofi")
            play https://zeno.fm/radio/cat-japonese-lofi-2
            ;;
        "deep space")
            play https://somafm.com/deepspaceone.pls
            ;;
        "ambient")
            play https://somafm.com/dronezone.pls
            ;;
        *)
            ;;
    esac
else
    main
fi
}

musicFromFolder ()
{
    FOLDERLIST=$(find $MUSICFOLDER -type d)

    folder=$(echo "stop
$FOLDERLIST" | sed -r 's/[ \t]+\/home/\n\/home/g' | $DMENU)

    if [ -n "$folder" ]; then
        if [ "$folder" = "stop" ]; then
            pkill $PLAYERTOKILL
        else
            play "$folder"
        fi
    else
        main
    fi
}

main ()
{
    choice=$(echo "stop
radio
background
local playlist" | $DMENU)

    case $choice in
        "stop")
            pkill $PLAYERTOKILL
            ;;
        "radio")
            musicFromLink
            ;;
        "background")
            background
            ;;
        "local playlist")
            musicFromFolder
            ;;
        *)
            ;;
    esac
}

main
