#!/bin/sh

DMENU="dmenu -l 5 -i"
cd $HOME/.config/jalupa_config/picom

options="restart
start
kill
use blur
use transparency"

choice=$(echo "$options" | $DMENU)

case "${choice}" in
    "restart")
        picom picom
        picom --experimental-backends &
        ;;
    "start")
        picom --experimental-backends &
        ;;
    "kill")
        pkill picom
        ;;
    "use blur")
        cp -f picom.blur picom.conf
        ;;
    "use transparency")
        cp -f picom.transparent picom.conf
        ;;
    *)
        ;;
esac
