#!/bin/sh

DMENU="dmenu -l 12 -i"
CMD="/bin/bash -c $1"
DMSCRIPTS="/bin/sh -c $HOME/.config/jalupa_config/dmenuscripts"

menu () { 
    printf "dmenu\n"
    printf "todo\n"
    printf "kill\n"
    printf "killall\n"
    printf "emacs\n"
    printf "firefox\n"
    printf "st\n"
    printf "kitty\n"
    printf "sasm\n"
    printf "mpv\n"
    printf "Harmonoid(music player)\n"
    printf "vlc\n"
    printf "joplin\n"
    printf "signal\n"
    printf "tutanota\n"
    printf "element\n"
    printf "steam\n"
    printf "heroic\n"
    printf "lutris\n"
    printf "bitwarden\n"
    printf "keepassxc\n"
    printf "veracrypt\n"
    printf "spotify\n"
    printf "zathura (pdf viewer)\n"
    printf "libreoffice\n"
    printf "xournal++\n"
    printf "blender\n"
    printf "krita\n"
    printf "protonvpn\n"
    printf "riseupvpn\n"
    printf "brave\n"
    printf "portmaster\n"
    printf "librewolf\n"
    printf "tor browser\n"
    printf "onionshare\n"
    printf "wireshark\n"
    printf "discord\n"
    printf "calculator\n"
    printf "camera\n"
    printf "thunar (file manager)\n"
    printf "store\n"
    printf "firefox uni\n"
    printf "firefox social\n"
    printf "firefox shopping\n"
    printf "firefox github\n"
    printf "virtmanager\n"
    printf "wifi\n"
    printf "wifi gui\n"
    printf "bluetooth\n"
    printf "clipboard\n"
    printf "clear-clipboard\n"
    printf "screenshot\n"
    printf "brightness\n"
    printf "volume\n"
    printf "pavucontrol (volume control)\n"
    printf "mount\n"
    printf "umount\n"
    printf "lock\n"
    printf "sleep\n"
    printf "shutdown\n"
    printf "restart\n"
    printf "picom\n"
    printf "translate\n"
    printf "music/radio\n"
    printf "background\n"
    printf "fix\n"
}

choice=$(menu | $DMENU ) || exit

case $choice in
    *\!) 
        $CMD "$(printf "%s" "${choice}" | cut -d'!' -f1)" # by https://tools.suckless.org/dmenu/scripts/dmenu_run_i
        return
        ;;
    "dmenu")
        dmenu_path | $DMENU "$@" | ${SHELL:-"/bin/sh"}
        return
        ;;
    "emacs")
        emacsclient -c -a 'emacs'
        return
        ;;
    "todo")
        $DMSCRIPTS/todo
        return
        ;;
    "kill")
        $DMSCRIPTS/kill
        return
        ;;
    "killall")
        $DMSCRIPTS/killall
        return
        ;;
    "firefox")
        $CMD firefox -p research
        return
        ;;
    "firefox uni")
        $CMD "firefox -p Uni"
        return
        ;;
    "firefox social")
        $CMD "firefox -p social"
        return
        ;;
    "firefox shopping")
        $CMD "firefox -p shopping"
        return
        ;;
    "firefox github")
        $CMD "firefox -p github"
        return
        ;;
    "discord")
        $CMD "firefox -p discord"
        return
        ;;
    "tor browser")
        $CMD torbrowser-launcher
        return
        ;;
    "librewolf")
        $CMD /home/jalupa/.local/share/flatpak/app/io.gitlab.librewolf-community/x86_64/stable/5d2af9f5bacd4fd599f80f84cbe8eee75731cead20f2a9936bfe700959d4012c/files/lib/librewolf
        return
        ;;
    "brave")
        $CMD brave
        return
        ;;
    "portmaster")
        $CMD "/opt/safing/portmaster/portmaster-start app"
        return
        ;;
    "st")
        $CMD st
        return
        ;;
    "kitty")
        $CMD kitty
        return
        ;;
    "sasm")
        $CMD sasm
        return
        ;;
    "mpv")
        $CMD "mpv --player-operation-mode=pseudo-gui"
        return
        ;;
    "Harmonoid(music player)")
        $CMD harmonoid
        return
        ;;
    "vlc")
        $CMD vlc
        return
        ;;
    "joplin")
        $CMD joplin-desktop
        return
        ;;
    "signal")
        $CMD /home/jalupa/.local/share/flatpak/app/org.signal.Signal/x86_64/stable/7ac884009d81a05ca7ccf26c88d9650eae6331a610f2eed95969028530caf0da/files/Signal/signal-desktop
        return
        ;;
    "element")
        $CMD element-desktop
        return
        ;;
    "steam")
        $CMD steam
        return
        ;;
    "heroic")
        $CMD /home/jalupa/.local/share/flatpak/app/com.heroicgameslauncher.hgl/x86_64/stable/d2ce4965ff3df7522f02c702e7cd3d7ae43e26daaa0af8f03b87b1ca20f287bf/files/bin/heroic/heroic
        return
        ;;
    "lutris")
        $CMD lutris
        return
        ;;
    "tutanota")
        $CMD /home/jalupa/.local/share/flatpak/app/com.tutanota.Tutanota/x86_64/stable/67dc915f61bdbbb792323b72ca5ac5277890d98f68333b8f9105b078c68d2f8f/files/lib/tutanota/tutanota-desktop
        return
        ;;
    "bitwarden")
        $CMD /home/jalupa/.local/share/flatpak/app/com.bitwarden.desktop/x86_64/stable/28565fb9c68c2a5b33867af5074d73770cb9779801628d8711e9b865cadbd983/files/Bitwarden/bitwarden
        return
        ;;
    "keepassxc")
        $CMD keepassxc
        return
        ;;
    "veracrypt")
        $CMD veracrypt
        return
        ;;
    "protonvpn")
        $CMD qomui-gui
        #$CMD protonvpn
        return
        ;;
    "riseupvpn")
        $CMD riseup-vpn-terminal
        return
        ;;
    "onionshare")
        $CMD onionshare
        return
        ;;
    "wireshark")
        $CMD wireshark
        return
        ;;
    "spotify")
        $CMD 
        return/home/jalupa/.local/share/flatpak/app/com.spotify.Client/x86_64/stable/c669b7e38957c40c984e849a0a61a3fc3d1aa47a81077dc492114a9879a11136/files/bin/spotify
        ;;
    "zathura (pdf viewer)")
        $CMD zathura
        return
        ;;
    "libreoffice")
        $CMD libreoffice
        return
        ;;
    "xournal++")
        $CMD xournalpp
        return
        ;;
    "blender")
        $CMD /home/jalupa/repos/utils/blender/blender
        return
        ;;
    "krita")
        $CMD krita
        return
        ;;
    "calculator")
        $CMD kcalc
        return
        ;;
    "camera")
        $CMD deepin-camera
        return
        ;;
    "thunar (file manager)")
        $CMD thunar
        return
        ;;
    "store")
        $CMD io.elementary.appcenter
        return
        ;;
    "virtmanager")
        $CMD virt-manager
        return
        ;;
    "wifi")
        $DMSCRIPTS/wifi
        return
        ;;
    "wifi gui")
        $CMD nm-connection-editor
        return
        ;;
    "bluetooth")
        $DMSCRIPTS/bluetooth 
        return
        ;;
    "clipboard")
        $DMSCRIPTS/clipboard
        return
        ;;
    "clear-clipboard")
        $DMSCRIPTS/clear-clipboard
        return
        ;;
    "screenshot")
        $DMSCRIPTS/screenshot
        return
        ;;
    "brightness")
        $DMSCRIPTS/brightness
        return
        ;;
    "volume")
        $DMSCRIPTS/volume
        return
        ;;
    "pavucontrol (volume control)")
        $CMD pavucontrol
        return
        ;;
    "mount")
        $DMSCRIPTS/'mount -m'
        return
        ;;
    "umount")
        $DMSCRIPTS/'mount -u'
        return
        ;;
    "lock")
        $CMD slock
        return
        ;;
    "sleep")
        systemctl suspend
        $CMD slock
        return
        ;;
    "shutdown")
        if [ "$(echo "yes\nno" | $DMENU)" = "yes" ]; then systemctl poweroff; fi
        return
        ;;
    "restart")
        if [ "$(echo "yes\nno" | $DMENU)" = "yes" ]; then systemctl reboot; fi
        return
        ;;
    "picom")
        $DMSCRIPTS/picom
        return
        ;;
    "translate")
        $DMSCRIPTS/translate
        return
        ;;
    "music/radio")
        $DMSCRIPTS/music
        return
        ;;
    "background")
        $DMSCRIPTS/changeBackground
        return
        ;;
    "fix")
        $DMSCRIPTS/fix
        return
        ;;
    *)
        echo "idk what happend. terminating..." && exit 0
        ;;
esac
