#!/bin/sh

DMENU="dmenu -l 12 -i"
CMD="/bin/bash -c $1"
DMSCRIPTS="/bin/sh -c $HOME/.config/jalupa_config/dmenuscripts"

menu () { 
    printf "dmenu\n"
    printf "todo\n"
    printf "kill\n"
    printf "killall\n"
    printf "emacs\n"
    printf "firefox\n"
    printf "st\n"
    printf "kitty\n"
    printf "sasm\n"
    printf "mpv\n"
    printf "Harmonoid(music player)\n"
    printf "vlc\n"
    printf "joplin\n"
    printf "signal\n"
    printf "tutanota\n"
    printf "element\n"
    printf "steam\n"
    printf "heroic\n"
    printf "lutris\n"
    printf "bitwarden\n"
    printf "keepassxc\n"
    printf "veracrypt\n"
    printf "spotify\n"
    printf "blender\n"
    printf "freecad\n"
    printf "krita\n"
    printf "protonvpn\n"
    printf "riseupvpn\n"
    printf "brave\n"
    printf "portmaster\n"
    printf "obs\n"
    printf "Mullvad Browser\n"
    printf "tor browser\n"
    printf "onionshare\n"
    printf "zathura (pdf viewer)\n"
    printf "libreoffice\n"
    printf "xournal++\n"
    printf "wireshark\n"
    printf "discord\n"
    printf "calculator\n"
    printf "camera\n"
    printf "nautilus (file manager)\n"
    printf "store\n"
    printf "Arduino IDE\n"
    printf "Android Studio\n"
    printf "firefox uni\n"
    printf "firefox social\n"
    printf "firefox shopping\n"
    printf "firefox github\n"
    printf "virtmanager\n"
    printf "alarm\n"
    printf "wifi\n"
    printf "wifi gui\n"
    printf "bluetooth\n"
    printf "clipboard\n"
    printf "clear-clipboard\n"
    printf "screenshot\n"
    printf "brightness\n"
    printf "volume\n"
    printf "pavucontrol (volume control)\n"
    printf "mount\n"
    printf "umount\n"
    printf "lock\n"
    printf "sleep\n"
    printf "shutdown\n"
    printf "restart\n"
    printf "picom\n"
    printf "translate\n"
    printf "music/radio\n"
    printf "background\n"
    printf "keybaord layout\n"
    printf "fix\n"
}

choice=$(menu | $DMENU ) || exit

case $choice in
    *\!) 
        $CMD "$(printf "%s" "${choice}" | cut -d'!' -f1)" # by https://tools.suckless.org/dmenu/scripts/dmenu_run_i
        return
        ;;
    "dmenu")
        dmenu_path | $DMENU "$@" | ${SHELL:-"/bin/sh"}
        return
        ;;
    "emacs")
        emacsclient -c -a 'emacs'
        return
        ;;
    "todo")
        $DMSCRIPTS/todo
        return
        ;;
    "kill")
        $DMSCRIPTS/kill
        return
        ;;
    "killall")
        $DMSCRIPTS/killall
        return
        ;;
    "firefox")
        $CMD firefox -p research
        return
        ;;
    "firefox uni")
        $CMD "firefox -p Uni"
        return
        ;;
    "firefox social")
        $CMD "firefox -p social"
        return
        ;;
    "firefox shopping")
        $CMD "firefox -p shopping"
        return
        ;;
    "firefox github")
        $CMD "firefox -p github"
        return
        ;;
    "discord")
        $CMD "firefox -p discord"
        return
        ;;
    "tor browser")
        $CMD torbrowser-launcher
        return
        ;;
    "Mullvad Browser")
        $CMD "flatpak run net.mullvad.MullvadBrowser"
        return
        ;;
    "brave")
        $CMD "flatpak run com.brave.Browser"
        return
        ;;
    "portmaster")
        $CMD "/opt/safing/portmaster/portmaster-start app"
        return
        ;;
    "obs")
        $CMD "flatpak run com.obsproject.Studio"
        return
        ;;
    "st")
        $CMD st
        return
        ;;
    "kitty")
        $CMD kitty
        return
        ;;
    "sasm")
        $CMD sasm
        return
        ;;
    "mpv")
        $CMD "mpv --player-operation-mode=pseudo-gui"
        return
        ;;
    "Harmonoid(music player)")
        $CMD harmonoid
        return
        ;;
    "vlc")
        $CMD vlc
        return
        ;;
    "joplin")
        $CMD joplin-desktop
        return
        ;;
    "signal")
        $CMD "flatpak run org.signal.Signal"
        return
        ;;
    "element")
        $CMD element-desktop
        return
        ;;
    "steam")
        $CMD steam
        return
        ;;
    "heroic")
        $CMD "flatpak run com.heroicgameslauncher.hgl"
        return
        ;;
    "lutris")
        $CMD lutris
        return
        ;;
    "tutanota")
        $CMD "flatpak run com.tutanota.Tutanota"
        return
        ;;
    "bitwarden")
        $CMD "flatpak run com.bitwarden.desktop"
        return
        ;;
    "keepassxc")
        $CMD keepassxc
        return
        ;;
    "veracrypt")
        $CMD veracrypt
        return
        ;;
    "protonvpn")
        $CMD qomui-gui
        #$CMD protonvpn
        return
        ;;
    "riseupvpn")
        $CMD riseup-vpn-terminal
        return
        ;;
    "onionshare")
        $CMD onionshare
        return
        ;;
    "wireshark")
        $CMD wireshark
        return
        ;;
    "spotify")
        $CMD "flatpak run com.spotify.Client"
        ;;
    "zathura (pdf viewer)")
        $CMD zathura
        return
        ;;
    "libreoffice")
        $CMD libreoffice
        return
        ;;
    "xournal++")
        $CMD xournalpp
        return
        ;;
    "blender")
        $CMD /opt/blender/blender
        return
        ;;
    "freecad")
        $CMD "flatpak run org.freecadweb.FreeCAD"
        return
        ;;
    "krita")
        $CMD krita
        return
        ;;
    "calculator")
        $CMD kcalc
        return
        ;;
    "camera")
        $CMD deepin-camera
        return
        ;;
    "nautilus (file manager)")
        $CMD nautilus
        return
        ;;
    "store")
        $CMD io.elementary.appcenter
        return
        ;;
    "Arduino IDE")
        $CMD "flatpak run cc.arduino.IDE2"
        return
        ;;
    "Android Studio")
        $CMD "flatpak run com.google.AndroidStudio"
        return
        ;;
    "virtmanager")
        $CMD virt-manager
        return
        ;;
    "alarm")
        $DMSCRIPTS/alarm
        return
        ;;
    "wifi")
        $DMSCRIPTS/wifi
        return
        ;;
    "wifi gui")
        $CMD nm-connection-editor
        return
        ;;
    "bluetooth")
        $DMSCRIPTS/bluetooth 
        return
        ;;
    "clipboard")
        $DMSCRIPTS/clipboard
        return
        ;;
    "clear-clipboard")
        $DMSCRIPTS/clear-clipboard
        return
        ;;
    "screenshot")
        $DMSCRIPTS/screenshot
        return
        ;;
    "brightness")
        $DMSCRIPTS/brightness
        return
        ;;
    "volume")
        $DMSCRIPTS/volume
        return
        ;;
    "pavucontrol (volume control)")
        $CMD pavucontrol
        return
        ;;
    "mount")
        $DMSCRIPTS/'mount -m'
        return
        ;;
    "umount")
        $DMSCRIPTS/'mount -u'
        return
        ;;
    "lock")
        $CMD slock
        return
        ;;
    "sleep")
        systemctl suspend
        $CMD slock
        return
        ;;
    "shutdown")
        if [ "$(echo "yes\nno" | $DMENU)" = "yes" ]; then systemctl poweroff; fi
        return
        ;;
    "restart")
        if [ "$(echo "yes\nno" | $DMENU)" = "yes" ]; then systemctl reboot; fi
        return
        ;;
    "picom")
        $DMSCRIPTS/picom
        return
        ;;
    "translate")
        $DMSCRIPTS/translate
        return
        ;;
    "music/radio")
        $DMSCRIPTS/music
        return
        ;;
    "background")
        $DMSCRIPTS/changeBackground
        return
        ;;
    "keybaord layout")
        $DMSCRIPTS/keyboard
        return
        ;;
    "fix")
        $DMSCRIPTS/fix
        return
        ;;
    *)
        echo "idk what happend. terminating..." && exit 0
        ;;
esac
