#!/bin/sh


DMENU="dmenu -l 5 -p"

levels="5
15
50
70
99"

current=$(amixer sget Master | awk -F "[][]" '/Left:/ { print $2 }')

end () {
    notify-send -a "volume" "set volume to $(amixer sget Master | awk -F "[][]" '/Left:/ { print $2 }') [$(amixer sget Master | awk -F "[][]" '/Left:/ { print $4 }')]"
    exit 0
}

getopts "idtms:" flag
case "${flag}" in
    i) #increase
        amixer set Master 5%+
        end
        ;;
    d) #decrease
        amixer set Master 5%-
        end
        ;;
    t) #toggle
        amixer set Master toggle
        amixer set Headphone on
        amixer set Front on
        amixer set Surround on
        amixer set Center on
        amixer set LFE on
        end
        ;;
    m) #toggle mute
        amixer -c 2 set Mic toggle
        if [  ! $? = 0 ]; then
            amixer -c 1 set Mic toggle
        notify-send -a "volume" "set microphone to $(amixer -c 1 sget Mic | awk -F "[][]" '/Mono:/ { print $2 }') [$(amixer -c 1 sget Mic | awk -F "[][]" '/Mono:/ { print $6 }')]"
    else
        notify-send -a "volume" "set microphone to $(amixer -c 2 sget Mic | awk -F "[][]" '/Mono:/ { print $2 }') [$(amixer -c 2 sget Mic | awk -F "[][]" '/Mono:/ { print $6 }')]"
        fi
        exit 0
        ;;
    s) #set
        amixer set Master $OPTARG%
        end
        ;;
    :)
        value=$(echo "$levels" | $DMENU " $current ")
        amixer set Master $value%
        end
        ;;
esac

value=$(echo "$levels" | $DMENU " $current ")
amixer set Master $value%
end
