#!/bin/sh


DMENU="dmenu -l 5 -p"

levels="5
15
50
70
99"

current=$(amixer sget Master | awk -F "[][]" '/Left:/ { print $2 }')

end () {
    notify-send -a "volume" "set volume to $(amixer sget Master | awk -F "[][]" '/Left:/ { print $2 }') [$(amixer sget Master | awk -F "[][]" '/Left:/ { print $4 }')]"
    exit 0
}

getopts "idtms:" flag
case "${flag}" in
    i) #increase
        amixer set Master 5%+
        end
        ;;
    d) #decrease
        amixer set Master 5%-
        end
        ;;
    t) #toggle
        amixer set Master toggle
        amixer set Headphone on
        amixer set Front on
        amixer set Surround on
        amixer set Center on
        amixer set LFE on
        end
        ;;
    m) #toggle mute
        pactl set-source-mute 'alsa_input.usb-0c76_USB_PnP_Audio_Device-00.mono-fallback' toggle
        # amixer variants
        # amixer -c 2 set Mic toggle
        # amixer set Capture toggle
        # notify-send -a "volume" "set microphone to $(amixer sget Capture | awk -F "[][]" '/Mono:/ { print $2 }') [$(amixer sget Capture | awk -F "[][]" '/Mono:/ { print $4 }')]"
        exit 0
        ;;
    s) #set
        amixer set Master $OPTARG%
        end
        ;;
    :)
        value=$(echo "$levels" | $DMENU " $current ")
        amixer set Master $value%
        end
        ;;
esac

value=$(echo "$levels" | $DMENU " $current ")
amixer set Master $value%
end
