#!/usr/bin/sh
#
# This script is copied from https://github.com/GeorgiChalakov01/wifi-control
# and has been edited to work for me
#
# TODO: check for internet after 3 sec, if not, ask for password

DMENU="dmenu -i -p "

case $(echo -e "CONNECT\nDISCONNECT\nWIFI ON\nWIFI OFF" | $DMENU "WIFI Options: " -l 4;) in
	CONNECT)
		wifiname=$(nmcli d wifi list | $DMENU "Select WIFI" -l 20 | cut -d' ' -f9);
        if [ -n "$wifiname" ]; then
            pass=$(echo "" | $DMENU "Password: ");
            if [ -n "$wifi" ]; then
                nmcli d wifi connect $wifiname password $pass
            else
                nmcli d wifi connect $wifiname
            fi
        fi

        sleep 5
        wget -q --spider https://duckduckgo.com
        if [ $? -eq 0 ]; then
            notify-send -a wifi "wifi activated!"
        else
            notify-send -a wifi "connection failed!"
        fi

        return
		;;
	DISCONNECT)
		internet=$(nmcli | grep "connected" | sed -n '1p' | cut -c 22-);
		nmcli con down id $internet;
        return
		;;
	"WIFI ON")
		nmcli radio wifi on;
        return
		;;
	"WIFI OFF")
		nmcli radio wifi off;
		;;
    *)
        echo "idk what happend. terminating..." && exit 0
        ;;
esac
